### ISSUE TITLE
Add OperatorHub release

### ISSUE THREAD

**Issue by vmuzikar** [keycloak-rel-testing/keycloak-rel#17]
* Use the existing [automation](https://github.com/keycloak/keycloak/blob/main/operator/app/scripts/create-olm-bundle.sh) for bundle creation
* Create PRs in
   * https://github.com/redhat-openshift-ecosystem/community-operators-prod
   * https://github.com/k8s-operatorhub/community-operators
   * See e.g.
      * https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/1117
      * https://github.com/k8s-operatorhub/community-operators/pull/1091

**Comment by vmuzikar** [comment]
This as to be done no sooner than in KC 20.0.0. Before that we're still releasing both legacy and the new Operator. Due to OLM technical limitations, the two Operators have to have different versions. As a result, the new Operator is using version 20.0.0-alpha.X in OLM even in KC 18 and 19 releases. See also: https://www.keycloak.org/2022/04/keycloak-1800-released.html#_operatorhub_versioning_scheme

**Comment by stianst** [comment]
Moved to https://github.com/keycloak-rel/keycloak-rel/issues/35
