### ISSUE TITLE
Add some details for a particular execution of the nightly and release workflows

### ISSUE THREAD

**Issue by stianst** [keycloak-rel-testing/keycloak-rel#38]
At the moment it is a bit hard to figure out what branches/versions/tags/etc was used for a specific run.

Notice messages could be useful here:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-notice-message

This should pop-up in the Annotations section for an execution.

Or perhaps a step that outputs the details, or creates a report or something like that. Maybe we would also want something that outputs everything that was created from a release?

**Comment by stianst** [comment]
@vmuzikar @jonkoops FIY

**Comment by hmlnarik** [comment]
For an example on how this is used, refer in existing code, refer to
https://github.com/keycloak/keycloak/blob/d048bf22fbf648f6b25f13223d7da0fc258ec5d2/testsuite/model/test-all-profiles.sh#L26
See "Annotations" section in e.g. https://github.com/keycloak/keycloak/actions/runs/2525820535

**Comment by stianst** [comment]
Moved to https://github.com/keycloak-rel/keycloak-rel/issues/31
